db_users:
  - username: zfonteno
    password: f3Fek*bw2&9@d2@!
db_specs:
  - host: localhost
    port: 3306
    name: ColonyEye

dropbox:
  - app_key: d7tqkcps28kfnas
    app_secret: 0lpipnnl5nkg5ne
    folder_path: /ColonyRack_data/

colony:
  - name: colony_1

matrix:
  - homeserver: https://matrix-client.matrix.org
  - username: colony.eye.app
  - password: jD7*o193nV%#pW